{
 "title": "Observability",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Uptime of Pods",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{service=\"backend\"}",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "up{service=\"frontend\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "No of requests/HTTP status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(flask_http_request_total) by (status)",
     "legendFormat": "HTTP {{ status }}"
    }
   ]
  },
  {
   "title": "Average response time - All requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum[30s])\n/\nrate(flask_http_request_duration_seconds_count[30s])",
     "legendFormat": "{{path}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Request rate under 250ms",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "increase(flask_http_request_duration_seconds_bucket{le=\"0.25\"}[30s]) \n/ ignoring (le) increase(flask_http_request_duration_seconds_count[30s])",
     "legendFormat": "{{path}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage (Pods/default)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"default\", container!=\"\", image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_resourcequota{namespace=\"default\", type=\"hard\",resource=\"requests.memory\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{namespace=\"default\", type=\"hard\",resource=\"limits.memory\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "CPU usage (Pods/default)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"default\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_resourcequota{namespace=\"default\", type=\"hard\",resource=\"requests.cpu\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{namespace=\"default\", type=\"hard\",resource=\"limits.cpu\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "Jaeger Tracing Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    { "service": "backend-service" }
   ]
  }
 ]
}